### ISSUE TITLE
Espresso and CoFFee code install

### ISSUE THREAD

**Issue by zhupeter618** [alexschimel/Espresso#2]
Dear Alexandre,

Thank you so much for your Matlab codes "Espresso and CoFFee" and I have installed them in the Matlab R2020b and try to use them for my research. But I meet some problem when I run them for my data.

The install directories are at the path E:\Espresso and E:\CoFFee-master.

The execution results show in my laptop and show some error information, please help me which problem I meet.

">> Espresso
==================================================================================================================
ESPRESSO v1.2.0 (powered by CoFFee v2.0.0-alpha.21)
Copyright (c) 2017-2024 Alexandre Schimel, Yoann Ladroit, NIWA
Licensed under the MIT License. See LICENSE file for details.
If you use this software, please acknowledge:
Alexandre Schimel (The Geological Survey of Norway), Yoann Ladroit (Kongsberg Discovery), and Sally Watson (NIWA).
==================================================================================================================
New session start at 07-Nov-2024 19:30:45. Please wait...
Espresso user folder: C:\Users\Administrator\Documents\Espresso.
Espresso config file: C:\Users\Administrator\Documents\Espresso\config.json.
Log file for this session: C:\Users\Administrator\Documents\Espresso\logs\Espresso_log_20241107_193045.txt.
CoFFee folder: E:\CoFFee-master.
Checking CoFFee version... CoFFee v2.0.0-alpha.21 found.
Parallel computing UNAVAILABLE. No GPU detected, but it could just be a driver issue. If you do have a GPU, update its driver and try this function again.
Creating main figure...
Updating list of files... Done.
Updating list of loaded lines... Done.
Wrong use imread>get_format_info (Line 545 )
undefine the file format.

error imread (Line 391)
        fmt_s = get_format_info(fullname);

error read_icon (Line 45)
[cdata,map,alpha] = imread(filename);

error create_display_tab (Line 240)
    'CData',read_icon('iconArrowUp.png'),...

error initialize_display (Line 37)
create_display_tab(main_figure,control_panel);

error Espresso (Line 189)
initialize_display(main_figure);

Hope you understand this error information and please check them for me. How can i fix them in my matlab.

**Comment by alexschimel** [comment]
Hi,

Thank you for using Espresso. 
 
The error in the execution is due to the fact that Espresso uses "[Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)". Git LFS handles large files by storing references to large files in the repository, but not the actual files themselves. So if you simply download the repository, you will download the references of large files instead of the large files themselves. Here, Espresso fails to read the file called "iconArrowUp.png" (in [folder assets\icons](https://github.com/alexschimel/Espresso/tree/master/assets/icons)) because it is a "large file" so what you downloaded is a reference file, instead of the original file. 

So, you get this error because you must have downloaded the software [using the "Download ZIP" method](https://docs.github.com/en/get-started/start-your-journey/downloading-files-from-github), when you should instead download the software [using the "repository cloning" method](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository), which will get you all the files, including the "large files".

Alex
